config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories, except: [:destroy]
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  validates :title, presence: true, length: { minimum: 6, maximum: 100 }
  validates :description, presence: true, length: { minimum: 10, maximum: 1000 }
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:show, :index]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def index
    @articles = Article.paginate(page: params[:page], per_page: 5).order(created_at: :desc)
  end

  def show
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description, category_ids: [])
  end

  def require_same_user
    return if current_user == @article.user || current_user.admin?

    flash[:alert] = 'You can only edit or delete your own articles'
    redirect_to @article
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
<div class="row justify-content-md-center">
  <div class="col-8 mt-4">
    <div class="card shadow mb-5 bg-white rounded text-center">
      <div class="card-header font-italic">
        by <%= link_to article.user.username, user_path(article.user), class: "header-link" if article.user %>
        <% if article.categories.any? %>
          <div class="mt-2"><%= render article.categories %></div>
        <% end %>
      </div>
      <div class="card-body">
        <h5 class="card-title"><%= link_to article.title, article_path(article), class:"text-info link-card"%></h5>
        <p class="card-text"><%= truncate(article.description, length: 100) %></p>
        <%= link_to "Show more", article_path(article), class: "btn btn-outline-info"%>
        <% if logged_in? && (current_user == article.user || current_user.admin?) %>
          <%= link_to "Edit", edit_article_path(article), class: "btn btn-outline-success"%>
          <%= link_to "Delete", article, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger"%>
        <% end %>
      </div>
      <div class="card-footer text-muted">
        <small> Created <%= time_ago_in_words(article.created_at) %> ago,
          edited <%= time_ago_in_words(article.updated_at) %> ago </small>
      </div>
    </div>
  </div>
</div>

app/views/articles/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'shared/errors', object: article%>
      <%= form_with(model: article, class: "shadow p-3 mb-2 bg-info rounded", local: true) do |form| %>
        <div class="form-group row">
          <%= form.label :title, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= form.text_field :title, class: "form-control shadow rounded", placeholder: "Title of article (100 characters max.)" %>
          </div>
        </div>

        <div class="form-group row">
          <%= form.label :description, class: "col-2 col-form-label text-light"%>
          <div class="col-10">
            <%= form.text_area :description, rows: 10, maxlength: 1000, class: "form-control shadow rounded", placeholder: "Description of article (1000 characters max.)" %>
          </div>
        </div>

        <div class="form-group row">
          <%= form.label :category, class: "col-2 col-form-label text-light"%>
          <div class="col-10">
            <%= form.collection_select(:category_ids, Category.all, :id, :name,
            { prompt: 'Tag your article with the items of the list (can be empty)' }, { multiple: true, size: 3, class: 'custom-select shadow rounded' }) %>
          </div>
        </div>

        <div class="form-group row justify-content-center">
          <%= form.submit class: "btn btn-outline-light bt-bg" %>
        </div>
      <% end %>
    </div>
    <div class="mb-3 mt-4">
      <%= link_to "Cancel and return to Articles", articles_path(article), class: "btn btn-outline-secondary btn-sm"%>
    </div>
  </div>
</div>

app/views/articles/edit.html.erb
<h1 id="title" class="text-center mt-4">Editing Article</h1>

<%= render 'form', article: @article %>

app/views/articles/index.html.erb
<h1 id="title" class="text-center mt-4">Nomada articles</h1>
<div class="container">
  <div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
  </div>
  <% @articles.each do |article| %>
    <%= render 'article', article: article %>
  <% end %>
  <div class="flickr_pagination mb-4">
    <%= will_paginate @articles, :container => false %>
  </div>
</div>

app/views/articles/new.html.erb
<h1 id="title" class="text-center mt-4">New Article</h1>

<%= render 'form', article: @article %>

app/views/articles/show.html.erb
<h1 id="title" class="text-center mt-4"><%= @article.title %></h1>
<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-8 mt-4">
      <div class="card shadow mb-5 bg-white rounded text-center">
        <div class="card-header font-italic">
          by <%= link_to @article.user.username, user_path(@article.user), class: "header-link" if @article.user %>
          <div class="mt-2"><%= link_to gravatar_for(@article.user, size: 120), user_path(@article.user) %></div>
          <% if @article.categories.any? %>
            <div class="mt-2"><%= render @article.categories %></div>
          <% end %>
        </div>
        <div class="card-body">
          <div class="card-text text-left"><%= simple_format(@article.description) %></div>
          <% if logged_in? && (current_user == @article.user || current_user.admin?) %>
            <%= link_to "Edit", edit_article_path(@article), class: "btn btn-outline-success"%>
            <%= link_to "Delete", @article, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger"%>
          <% end %>
        </div>
        <div class="card-footer text-muted">
          <small> Created <%= time_ago_in_words(@article.created_at) %> ago,
            edited <%= time_ago_in_words(@article.updated_at) %> ago </small>
        </div>
      </div>
    </div>
  </div>
</div>