config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories, except: [:destroy]
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :article_categories
  has_many :articles, through: :article_categories
  has_one_attached :image
  validates :name, presence: true, uniqueness: { case_sensitive: false }, length: { minimum: 3, maximum: 25 }
  validate :acceptable_image

  private

  def acceptable_image
    return unless image.attached?

    unless image.byte_size <= 5.megabytes
      errors.add(:image, 'is too big. Your image must be 5 megabytes maximum.')
    end

    acceptable_types = ['image/jpeg', 'image/png']
    unless acceptable_types.include?(image.content_type)
      errors.add(:image, 'must be a JPEG or PNG')
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:show, :index]
  before_action :require_admin, except: [:index, :show]

  def index
    @categories = Category.paginate(page: params[:page], per_page: 5).order(created_at: :desc)
  end

  def show
    @articles = @category.articles.paginate(page: params[:page], per_page: 5)
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    @category = Category.new(category_params)
    @category.image.attach(category_params[:image])
    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_path, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name, :image)
  end

  def require_admin
    return if logged_in? && current_user.admin?

    flash[:alert] = 'You can not perform that action on the categories'
    redirect_to categories_path
  end
end

app/views/categories/_category.html.erb
<%= link_to category.name, category_path(category), class: 'badge badge-pill badge-light mr-1' %>

app/views/categories/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'shared/errors', object: category%>
      <%= form_with(model: category, class: "shadow p-3 mb-2 bg-info rounded", local: true) do |form| %>
        <div class="form-group row">
          <%= form.label :name, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= form.text_field :name, minLength: 3, maxlength: 25, class: "form-control shadow rounded", placeholder: "Name of category" %>
            <label class="mt-2 btn btn-light">
              Choose category image
              <span style="display:none;">
                <%= form.file_field :image %>
              </span>
            </label>
          </div>
        </div>
        <div class="form-group row justify-content-center">
          <%= form.submit class: "btn btn-outline-light bt-bg" %>
        </div>
      <% end %>
    </div>
    <div class="mb-3 mt-4">
      <%= link_to "Cancel and return to categories", categories_path, class: "btn btn-outline-secondary btn-sm"%>
    </div>
  </div>
</div>

app/views/categories/edit.html.erb
<h1 id="title" class="text-center mt-4">Editing Category [<%= @category.name %>]</h1>

<%= render 'form', category: @category %>

app/views/categories/index.html.erb
<h1 id="title" class="text-center mt-4">Nomada Categories</h1>
<div class="container">
  <div class="flickr_pagination">
    <%= will_paginate @categories, :container => false %>
  </div>
  <% @categories.each do |category| %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card shadow mb-5 bg-white rounded text-center">
          <div class="card-header font-italic">
            <%= link_to category.name, category, class: "header-link" %>
          </div>
          <div class="card-body">
            <h5 class="card-title">
              <% if category.image.attached? %>
                <%= image_tag category.image, alt: category.name, height: 120, class: 'shadow rounded' %>
              <% end %>
            </h5>
            <p class="card-text"><%= pluralize(category.articles.count, 'article') %> posted for this category</p>
            <%= link_to "View category", category, class: "btn btn-outline-info"%>
            <% if logged_in? && current_user.admin? %>
              <%= link_to "Edit category name", edit_category_path(category), class: "btn btn-outline-success"%>
            <% end %>
          </div>
          <div class="card-footer text-muted">
            <small> </small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <div class="flickr_pagination mb-4">
    <%= will_paginate @categories, :container => false %>
  </div>
</div>

app/views/categories/new.html.erb
<h1 id="title" class="text-center mt-4">Create a new category</h1>

<%= render 'form', category: @category %>

app/views/categories/show.html.erb
<h1 id="title" class="text-center mt-4">Category [<%= @category.name %>]</h1>
<% if logged_in? && current_user.admin? %>
  <div class="text-center mt-4">
    <%= link_to 'Edit category name', edit_category_path(@category), class: 'btn btn-outline-success'%>
  </div>
<% end %>
<div class="text-center mt-4">
  <% if @category.image.attached? %>
    <%= image_tag @category.image, alt: @category.name, height: 320, class: 'shadow rounded' %>
  <% end %>
</div>

<h3 id="title" class="text-center mt-4">Articles</h3>
<div class="container">
  <div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
  </div>
  <% @articles.each do |article| %>
    <%= render 'articles/article', article: article %>
  <% end %>
  <div class="flickr_pagination mb-4">
    <%= will_paginate @articles, :container => false %>
  </div>
</div>