config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories, except: [:destroy]
end

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="py-4 bg-dark text-white-50">
  <div class="container text-center">
    <small>Copyright &copy; Nomada Blog - 2020</small>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |name, msg| %>
    <div class="alert alert-<%= name == 'notice' ? 'success' : 'danger' %> alert-dismissible fade show" role="alert">
      <%= msg %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light">
  <%= link_to "Nomada", root_path, class: "navbar-brand header-link", id: "logo" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to current_user&.admin? ? 'Manage bloggers' : 'Bloggers', users_path, class: "nav-link header-link"%>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle header-link" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Articles
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <% if logged_in? %>
            <%= link_to "Create new article", new_article_path, class: "dropdown-item"%>
          <% end %>
          <%= link_to articles_path, class: 'dropdown-item' do %>
            View articles <%= content_tag :span, Article.count, class: 'badge badge-info' %>
          <% end %>
          <%# <div class="dropdown-divider"></div> %>
          <%# <a class="dropdown-item" href="#">Something else here</a> %>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle header-link" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Categories
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <% if logged_in? && current_user.admin? %>
            <%= link_to "Create new category", new_category_path, class: "dropdown-item"%>
          <% end %>
          <%= link_to "View categories", categories_path, class: "dropdown-item"%>
          <div class="dropdown-divider"></div>
          <% Category.all.each do |category| %>
            <%= link_to category.name, category_path(category), class: "dropdown-item"%>
          <% end %>
        </div>
      </li>
      <% if logged_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle header-link" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= current_user.admin? ? 'Admin' : current_user.username %>'s profile
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "View profile", user_path(current_user), class: "dropdown-item"%>
            <%= link_to 'Edit profile', edit_user_path(current_user), class: 'dropdown-item'%>
          </div>
        </li>
        <li class="nav-item">
          <%= link_to 'Logout', logout_path, class: 'nav-link header-link', method: :delete %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Log in', login_path, class: 'nav-link header-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign up', signup_path, class: 'nav-link header-link' %>
        </li>
      <% end %>
    </ul>
    <%# <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-light my-2 my-sm-0" type="submit">Search</button>
    </form> %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nomada Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column">
    <div id='page-content'>
      <%= render "layouts/navigation" %>
      <%= render "layouts/messages" %>
      <%= yield %>
    </div>
    <%= render "layouts/footer" %>
  </body>
</html>